# Multiple Linear Regresion with One Variable (Lecture: 02)

__Author__: Pablo César Rodríguez Aguayo

__Subject__: Machine Learning

__Date__: 26/02/2018

In [1]:
%matplotlib inline
import sys
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#from terminaltables import AsciiTable
from mpl_toolkits.mplot3d import Axes3D
from numpy.polynomial.polynomial import polyfit
sns.set(color_codes=True)
sns.set_style("whitegrid")

In [2]:
dataset = pd.read_csv('bike_dataset.csv')
dataset = dataset.drop(columns=['instant', 'dteday'])
dataset.head()

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [3]:
normalized_df=(dataset-dataset.mean())/dataset.std()
normalized_df.head()

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,-1.347291,-1.000684,-1.599066,-0.171863,1.497783,-1.470218,1.109667,-0.826097,-0.679481,1.249316,-0.387626,-0.753218,-1.924153,-1.816709
1,-1.347291,-1.000684,-1.599066,-0.171863,-1.495054,-1.470218,1.109667,-0.720601,-0.740146,0.478785,0.749089,-1.044499,-1.913899,-1.911691
2,-1.347291,-1.000684,-1.599066,-0.171863,-0.996248,0.679241,-0.725551,-1.633538,-1.748570,-1.338358,0.746121,-1.060519,-1.555624,-1.628810
3,-1.347291,-1.000684,-1.599066,-0.171863,-0.497441,0.679241,-0.725551,-1.613675,-1.609168,-0.263001,-0.389562,-1.077996,-1.411417,-1.518858
4,-1.347291,-1.000684,-1.599066,-0.171863,0.001365,0.679241,-0.725551,-1.466410,-1.503941,-1.340576,-0.046275,-1.115863,-1.370398,-1.499242

In [4]:
# Data split into x and y
x = normalized_df.iloc[:,:-1].values
y = normalized_df.iloc[:,-1].values

In [5]:
# start trainning
# n is the number of features and m is the number of samples of training set
m, n = x.shape

# define theta as zero
theta = np.zeros(n)
theta = theta.reshape(n,1)

# iterations to update theta and minimize J
iterations = 1500

# alpha the learning rate in gradient descent update formula
alpha = 0.01

In [6]:
def hypothesis(x,theta):
    return np.dot(x,theta)

In [7]:
def compute_cost(x, y, theta):
    loss = hypothesis(x,theta)-y
    cost = np.sum(loss ** 2)/(2*m)
    return cost,loss

In [8]:
compute_cost(x,y,theta)

(364.99999999999994,
 array([[1.81670867, 1.91169056, 1.62880972, ..., 1.63293936, 1.39806568,
         0.91644556],
        [1.81670867, 1.91169056, 1.62880972, ..., 1.63293936, 1.39806568,
         0.91644556],
        [1.81670867, 1.91169056, 1.62880972, ..., 1.63293936, 1.39806568,
         0.91644556],
        ...,
        [1.81670867, 1.91169056, 1.62880972, ..., 1.63293936, 1.39806568,
         0.91644556],
        [1.81670867, 1.91169056, 1.62880972, ..., 1.63293936, 1.39806568,
         0.91644556],
        [1.81670867, 1.91169056, 1.62880972, ..., 1.63293936, 1.39806568,
         0.91644556]]))

In [9]:
def gradient_descent(x,x_tran,y,theta,alpha,iterations):
    for i in range(iterations):
        cost,loss = compute_cost(x,y,theta)
        gradient = np.dot(x_tran,(loss))
        theta = theta - alpha*(gradient/m)
    return theta

In [10]:
alpha_rates = [0.01,0.03,0.1,0.3,1,2,3]
for i in range(len(alpha_rates)):
    theta = np.zeros(n)
    theta = theta.reshape(n,1) # make sure theta not updated and it is always zero before new train
    x_transposed = x.transpose()
    gradient_descent(x = x,x_tran = x_transposed,y = y,theta = theta,alpha = alpha_rates[i],iterations = (iterations+1))

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 364.99999999999994

Iteration #100 ====== cost = 364.99999999999994

Iteration #150 ====== cost = 364.99999999999994

Iteration #200 ====== cost = 365.0

Iteration #250 ====== cost = 365.0

Iteration #300 ====== cost = 365.0

Iteration #350 ====== cost = 364.99999999999994

Iteration #400 ====== cost = 364.99999999999994

Iteration #450 ====== cost = 365.0

Iteration #500 ====== cost = 365.0

Iteration #550 ====== cost = 365.0

Iteration #600 ====== cost = 365.0

Iteration #650 ====== cost = 365.0

Iteration #700 ====== cost = 365.0

Iteration #750 ====== cost = 365.0

Iteration #800 ====== cost = 365.0

Iteration #850 ====== cost = 365.0

Iteration #900 ====== cost = 365.00000000000006

Iteration #950 ====== cost = 365.0

Iteration #1000 ====== cost = 365.00000000000006

Iteration #1050 ====== cost = 365.00000000000006

Iteration #1100 ====== cost = 365.00000000000006

Iteration #1150 ====== cost = 365.00000000000006

Iteration #1200 ====== cost = 365.00000000000006

Iteration #1250 ====== cost = 365.00000000000006

Iteration #1300 ====== cost = 365.00000000000006

Iteration #1350 ====== cost = 365.00000000000006

Iteration #1400 ====== cost = 365.00000000000006

Iteration #1450 ====== cost = 365.00000000000006

Iteration #1500 ====== cost = 365.00000000000006

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 364.99999999999994

Iteration #100 ====== cost = 365.0

Iteration #150 ====== cost = 365.0

Iteration #200 ====== cost = 365.0

Iteration #250 ====== cost = 365.0

Iteration #300 ====== cost = 365.00000000000006

Iteration #350 ====== cost = 365.00000000000006

Iteration #400 ====== cost = 365.00000000000006

Iteration #450 ====== cost = 365.00000000000006

Iteration #500 ====== cost = 365.00000000000006

Iteration #550 ====== cost = 365.00000000000006

Iteration #600 ====== cost = 365.00000000000006

Iteration #650 ====== cost = 365.00000000000006

Iteration #700 ====== cost = 365.00000000000006

Iteration #750 ====== cost = 365.00000000000006

Iteration #800 ====== cost = 365.00000000000006

Iteration #850 ====== cost = 365.00000000000006

Iteration #900 ====== cost = 365.00000000000006

Iteration #950 ====== cost = 365.00000000000006

Iteration #1000 ====== cost = 365.0

Iteration #1050 ====== cost = 365.0

Iteration #1100 ====== cost = 365.0

Iteration #1150 ====== cost = 365.0

Iteration #1200 ====== cost = 365.00000000000006

Iteration #1250 ====== cost = 365.0

Iteration #1300 ====== cost = 365.0

Iteration #1350 ====== cost = 365.0

Iteration #1400 ====== cost = 365.0

Iteration #1450 ====== cost = 365.0

Iteration #1500 ====== cost = 365.0

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 365.0

Iteration #100 ====== cost = 365.00000000000006

Iteration #150 ====== cost = 365.00000000000006

Iteration #200 ====== cost = 365.00000000000006

Iteration #250 ====== cost = 365.00000000000006

Iteration #300 ====== cost = 365.00000000000006

Iteration #350 ====== cost = 365.00000000000006

Iteration #400 ====== cost = 365.0

Iteration #450 ====== cost = 365.0

Iteration #500 ====== cost = 365.0

Iteration #550 ====== cost = 365.0

Iteration #600 ====== cost = 365.0

Iteration #650 ====== cost = 365.0

Iteration #700 ====== cost = 365.0

Iteration #750 ====== cost = 365.0

Iteration #800 ====== cost = 364.99999999999994

Iteration #850 ====== cost = 364.99999999999994

Iteration #900 ====== cost = 364.99999999999994

Iteration #950 ====== cost = 364.99999999999994

Iteration #1000 ====== cost = 364.99999999999994

Iteration #1050 ====== cost = 364.99999999999983

Iteration #1100 ====== cost = 364.99999999999983

Iteration #1150 ====== cost = 364.99999999999983

Iteration #1200 ====== cost = 364.99999999999983

Iteration #1250 ====== cost = 364.99999999999983

Iteration #1300 ====== cost = 364.99999999999983

Iteration #1350 ====== cost = 364.99999999999983

Iteration #1400 ====== cost = 364.9999999999998

Iteration #1450 ====== cost = 364.9999999999998

Iteration #1500 ====== cost = 364.9999999999998

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 365.00000000000006

Iteration #100 ====== cost = 365.0

Iteration #150 ====== cost = 365.0

Iteration #200 ====== cost = 365.0

Iteration #250 ====== cost = 365.0

Iteration #300 ====== cost = 364.99999999999994

Iteration #350 ====== cost = 364.99999999999983

Iteration #400 ====== cost = 364.99999999999983

Iteration #450 ====== cost = 364.99999999999983

Iteration #500 ====== cost = 364.99999999999983

Iteration #550 ====== cost = 364.9999999999998

Iteration #600 ====== cost = 364.99999999999983

Iteration #650 ====== cost = 364.99999999999994

Iteration #700 ====== cost = 364.99999999999983

Iteration #750 ====== cost = 364.99999999999983

Iteration #800 ====== cost = 364.99999999999994

Iteration #850 ====== cost = 364.99999999999994

Iteration #900 ====== cost = 364.99999999999983

Iteration #950 ====== cost = 364.99999999999983

Iteration #1000 ====== cost = 364.99999999999983

Iteration #1050 ====== cost = 364.99999999999983

Iteration #1100 ====== cost = 364.99999999999983

Iteration #1150 ====== cost = 364.99999999999983

Iteration #1200 ====== cost = 364.99999999999983

Iteration #1250 ====== cost = 364.99999999999983

Iteration #1300 ====== cost = 364.99999999999983

Iteration #1350 ====== cost = 364.99999999999983

Iteration #1400 ====== cost = 364.99999999999983

Iteration #1450 ====== cost = 364.99999999999983

Iteration #1500 ====== cost = 364.99999999999983

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 48831634071.632355

Iteration #100 ====== cost = 2.6721970736468385e+49

Iteration #150 ====== cost = 1.462297420419272e+88

Iteration #200 ====== cost = 8.002081009865893e+126

Iteration #250 ====== cost = 4.378951887236226e+165

Iteration #300 ====== cost = 2.3962791187802603e+204

Iteration #350 ====== cost = 1.3113077656412562e+243

Iteration #400 ====== cost = 7.175825398446604e+281

/home/ospcx/anaconda3/envs/pyml/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/ospcx/anaconda3/envs/pyml/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in square
  This is separate from the ipykernel package so we can avoid doing imports until

Iteration #450 ====== cost = inf

Iteration #500 ====== cost = inf

Iteration #550 ====== cost = inf

Iteration #600 ====== cost = inf

Iteration #650 ====== cost = inf

Iteration #700 ====== cost = inf

Iteration #750 ====== cost = inf

Iteration #800 ====== cost = inf

/home/ospcx/anaconda3/envs/pyml/lib/python3.6/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in subtract

Iteration #850 ====== cost = nan

Iteration #900 ====== cost = nan

Iteration #950 ====== cost = nan

Iteration #1000 ====== cost = nan

Iteration #1050 ====== cost = nan

Iteration #1100 ====== cost = nan

Iteration #1150 ====== cost = nan

Iteration #1200 ====== cost = nan

Iteration #1250 ====== cost = nan

Iteration #1300 ====== cost = nan

Iteration #1350 ====== cost = nan

Iteration #1400 ====== cost = nan

Iteration #1450 ====== cost = nan

Iteration #1500 ====== cost = nan

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 6.757244935561463e+48

Iteration #100 ====== cost = 5.8455521621455344e+125

Iteration #150 ====== cost = 5.056865691005926e+202

Iteration #200 ====== cost = 4.374589415602274e+279

Iteration #250 ====== cost = inf

Iteration #300 ====== cost = inf

Iteration #350 ====== cost = inf

Iteration #400 ====== cost = inf

Iteration #450 ====== cost = nan

Iteration #500 ====== cost = nan

Iteration #550 ====== cost = nan

Iteration #600 ====== cost = nan

Iteration #650 ====== cost = nan

Iteration #700 ====== cost = nan

Iteration #750 ====== cost = nan

Iteration #800 ====== cost = nan

Iteration #850 ====== cost = nan

Iteration #900 ====== cost = nan

Iteration #950 ====== cost = nan

Iteration #1000 ====== cost = nan

Iteration #1050 ====== cost = nan

Iteration #1100 ====== cost = nan

Iteration #1150 ====== cost = nan

Iteration #1200 ====== cost = nan

Iteration #1250 ====== cost = nan

Iteration #1300 ====== cost = nan

Iteration #1350 ====== cost = nan

Iteration #1400 ====== cost = nan

Iteration #1450 ====== cost = nan

Iteration #1500 ====== cost = nan

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 6.591130989529458e+68

Iteration #100 ====== cost = 5.7532169960101934e+165

Iteration #150 ====== cost = 5.021824912258883e+262

Iteration #200 ====== cost = inf

Iteration #250 ====== cost = inf

Iteration #300 ====== cost = inf

Iteration #350 ====== cost = nan

Iteration #400 ====== cost = nan

Iteration #450 ====== cost = nan

Iteration #500 ====== cost = nan

Iteration #550 ====== cost = nan

Iteration #600 ====== cost = nan

Iteration #650 ====== cost = nan

Iteration #700 ====== cost = nan

Iteration #750 ====== cost = nan

Iteration #800 ====== cost = nan

Iteration #850 ====== cost = nan

Iteration #900 ====== cost = nan

Iteration #950 ====== cost = nan

Iteration #1000 ====== cost = nan

Iteration #1050 ====== cost = nan

Iteration #1100 ====== cost = nan

Iteration #1150 ====== cost = nan

Iteration #1200 ====== cost = nan

Iteration #1250 ====== cost = nan

Iteration #1300 ====== cost = nan

Iteration #1350 ====== cost = nan

Iteration #1400 ====== cost = nan

Iteration #1450 ====== cost = nan

Iteration #1500 ====== cost = nan

In [11]:
# now we know best alpha so get our theta by this value of alpha = 0.03
x_transposed = x.transpose()
theta = gradient_descent(x = x,x_tran = x_transposed,y = y,theta = theta,alpha = 0.03,iterations = (iterations+1))

Iteration #0 ====== cost = 364.99999999999994

Iteration #50 ====== cost = 364.99999999999994

Iteration #100 ====== cost = 365.0

Iteration #150 ====== cost = 365.0

Iteration #200 ====== cost = 365.0

Iteration #250 ====== cost = 365.0

Iteration #300 ====== cost = 365.00000000000006

Iteration #350 ====== cost = 365.00000000000006

Iteration #400 ====== cost = 365.00000000000006

Iteration #450 ====== cost = 365.00000000000006

Iteration #500 ====== cost = 365.00000000000006

Iteration #550 ====== cost = 365.00000000000006

Iteration #600 ====== cost = 365.00000000000006

Iteration #650 ====== cost = 365.00000000000006

Iteration #700 ====== cost = 365.00000000000006

Iteration #750 ====== cost = 365.00000000000006

Iteration #800 ====== cost = 365.00000000000006

Iteration #850 ====== cost = 365.00000000000006

Iteration #900 ====== cost = 365.00000000000006

Iteration #950 ====== cost = 365.00000000000006

Iteration #1000 ====== cost = 365.0

Iteration #1050 ====== cost = 365.0

Iteration #1100 ====== cost = 365.0

Iteration #1150 ====== cost = 365.0

Iteration #1200 ====== cost = 365.00000000000006

Iteration #1250 ====== cost = 365.0

Iteration #1300 ====== cost = 365.0

Iteration #1350 ====== cost = 365.0

Iteration #1400 ====== cost = 365.0

Iteration #1450 ====== cost = 365.0

Iteration #1500 ====== cost = 365.0

In [13]:
# feature scaling and adding one to attend term theta0
test = np.zeros(2)
test[0] = 1650
test[1] = 3
test = test.reshape(1,2)
test = test - std_scaler.mean_
test = test / (sdv_0,sdv_1)

# appending ones to our x 
one = np.ones(1)
one = one.reshape(1,1)
test = np.append(one,test,axis =1)

NameError: name 'std_scaler' is not defined